# Generated by Django 5.0.2 on 2025-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
