# Generated by Django 5.0.2 on 2025-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
        migrations.AddField(
            model_name="project",
            name="owner_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
