# Generated by Django 5.2.6 on 2025-12-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model_url',
        ),
        migrations.AddField(
            model_name='project',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/models/'),
        ),
    ]
