# Generated by Django 5.0.2 on 2026-01-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_owner_id'),
        ('portfolio', '0002_remove_project_owner_project_owner_id'),
    ]

    operations = [
    ]
