# Generated by Django 5.0.2 on 2026-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_merge_20260108_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills_used',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='project',
            name='has_3d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/models/'),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
