"""
Django settings for auth_service project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import sys
# Base directory (corrected)
BASE_DIR = Path(__file__).resolve().parent.parent.parent

sys.path.append(os.path.join(BASE_DIR, "src"))
# Load environment variables
load_dotenv(BASE_DIR / ".env")

# Security
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-secret-for-dev")
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = ["*"]

# Database (Local Development Settings)


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}


# Installed Apps
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "src.main.apps.MainConfig",

    "corsheaders",
    "rest_framework",
    "drf_yasg",
    "rest_framework_simplejwt.token_blacklist",
    "social_django",

    "users",
]

# Middleware
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # MUST be first
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "social_django.middleware.SocialAuthExceptionMiddleware",
]

# URL configuration
ROOT_URLCONF = "src.main.urls"

# Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "src.main.wsgi.application"
ASGI_APPLICATION = "src.main.asgi.application"

# ============================================
#              CORS SETTINGS
# ============================================

# ALLOW ONLY SPECIFIC FRONTEND ORIGINS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Allow credentials (JWT cookies if needed)
CORS_ALLOW_CREDENTIALS = True

# Allow methods
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# Allow all headers
CORS_ALLOW_HEADERS = ["*"]

# ============================================
#           AUTHENTICATION / JWT
# ============================================

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        
    ),
    "EXCEPTION_HANDLER": "src.common.exceptions.custom_exception.custom_exception_handler",
}






# ============================================
#                 EMAIL SETTINGS
# ============================================

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "no-reply@architech.local"

# ============================================
#                 OTP SETTINGS
# ============================================

OTP_TTL_MINUTES = 10
OTP_LENGTH = 6

# ============================================
#              STATIC FILES
# ============================================

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================
#                 SWAGGER
# ============================================

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
        }
    }
}

# ============================================
#           SOCIAL AUTH CONFIG
# ============================================

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "users.backends.CustomModelBackend",
    "social_core.backends.google.GoogleOAuth2",
)

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
)


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("GOOGLE_OAUTH2_KEY", "")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("GOOGLE_OAUTH2_SECRET", "")
SOCIAL_AUTH_USER_FIELDS = ["email", "first_name", "last_name"]

SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/api/auth/login/"
SOCIAL_AUTH_LOGIN_ERROR_URL = "/login/"


JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "ALGORITHM": os.getenv("JWT_ALGORITHM", "HS256"),
    "SIGNING_KEY": os.getenv("JWT_SECRET_KEY"),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_CLAIM": "user_id",
}

print(">>> JWT_SECRET_KEY =", JWT_SECRET_KEY)



# ============================
# RabbitMQ Settings
# ============================
RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", "rabbitmq")
RABBITMQ_PORT = int(os.getenv("RABBITMQ_PORT", 5672))
RABBITMQ_USER = os.getenv("RABBITMQ_USER", "admin")
RABBITMQ_PASS = os.getenv("RABBITMQ_PASS", "admin")
RABBITMQ_QUEUE = os.getenv("RABBITMQ_QUEUE", "user_events")
print(f"DEBUG_SETTINGS_LOAD: JWT_SECRET_KEY={os.getenv('JWT_SECRET_KEY')}")
print(f"DEBUG_SETTINGS_LOAD: SIGNING_KEY={SIMPLE_JWT.get('SIGNING_KEY')}")
