# Generated by Django 5.0.2 on 2025-11-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mfadevice_mfa_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfadevice',
            name='mfa_type',
        ),
    ]
