# Generated by Django 5.2.6 on 2025-11-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_mfadevice_mfa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_mfa',
            field=models.BooleanField(default=False),
        ),
    ]
