# Generated by Django 5.2.6 on 2025-12-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(help_text='User ID from auth_service', max_length=255),
        ),
    ]
