# Generated by Django 5.2.6 on 2025-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_sender_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
